site_name: Home Lab Documentation
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: pink
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
    - 'Home': 'index.md'
    - 'Home Assistant': 'homeassistant.md'
    - 'Home Lab': 'homelab.md'
    - 'Network': 'network.md'
    - 'Feature Test': 'featurehassio.md'